# yaml-language-server: $schema=https://raw.githubusercontent.com/F1bonacc1/process-compose/main/schemas/process-compose-schema.json

version: "0.5"

processes:
  sanitycheck:
    command: "NV=$(nats-server -v) && echo Found NATS: $${NV}"
    availability:
      restart: "exit_on_failure"
  prepare:
    command: mkdir -p ./nats-cluster
    depends_on:
      sanitycheck:
        condition: process_completed_successfully

  nats-config:
    command: |
      for i in 0 1 2; do
        cat > ./nats-cluster/n$${i}.conf <<NATSEOF
      server_name: N$${i}
      listen: "127.0.0.1:422$${i}"
      http_port: 822$${i}

      jetstream {
        store_dir: "./data/n$${i}"
      }

      cluster {
        name: nats-cluster
        listen: "127.0.0.1:622$${i}"
        connect_retries: 30
        pool_size: 3
        compression: {
          mode: "accept"
        }
        routes: [
          "nats://127.0.0.1:6220"
          "nats://127.0.0.1:6221"
          "nats://127.0.0.1:6222"
        ]
      }
      NATSEOF
      done
      echo "Generated NATS configs for nodes 0, 1, 2"
    working_dir: "."
    depends_on:
      prepare:
        condition: process_completed_successfully
  pc_log:
    command: "tail -f -n100 process-compose-${USER}.log"
    working_dir: "/tmp"

  nats-cluster-node:
    command: nats-server -c ./nats-cluster/n$${PC_REPLICA_NUM}.conf
    replicas: 3
    depends_on:
      nats-config:
        condition: process_completed_successfully
    description: "NATS Server instance N{{ .PC_REPLICA_NUM }} (port 422{{ .PC_REPLICA_NUM }}) with JetStream enabled"
    readiness_probe:
      http_get:
        host: 127.0.0.1
        path: "/healthz?js-server-only=true"
        port: "822{{ .PC_REPLICA_NUM }}"
      initial_delay_seconds: 5
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3
    # ready_log_line: "Server is ready"

  ha-store:
    command: ./ha-store -nats-url nats://localhost:4220,nats://localhost:4221,nats://localhost:4222 -replicas 3 -throttle-speed 300
    description: "HA Store API server"
    depends_on:
      nats-cluster-node-0:
        condition: process_healthy
      nats-cluster-node-1:
        condition: process_healthy
      nats-cluster-node-2:
        condition: process_healthy
    availability:
      restart: always
    truncate_log: true

  nats-top:
    command: nats-top -s localhost -m 8220
    depends_on:
      nats-cluster-node-0:
        condition: process_healthy
      nats-cluster-node-1:
        condition: process_healthy
      nats-cluster-node-2:
        condition: process_healthy
    is_interactive: true
